#!/usr/bin/env node
/**
 * embed-version.mjs
 *
 * Runs after tsup build to write a version metadata file at
 * src/version.ts (checked in) and dist/version-meta.json (gitignored).
 *
 * The TypeScript file is imported by the CLI at runtime so every build
 * always reports the exact version it was compiled from, without having
 * to parse package.json at runtime.
 *
 * Usage:
 *   node scripts/embed-version.mjs
 *
 * Called automatically by the "build" npm script via postbuild hook.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));

// Git metadata (best-effort)
function git(cmd) {
  try {
    return execSync(cmd, { cwd: ROOT, encoding: "utf-8" }).trim();
  } catch {
    return "";
  }
}

const commitHash  = git("git rev-parse --short HEAD");
const commitDate  = git("git log -1 --format=%ci");
const branch      = git("git rev-parse --abbrev-ref HEAD");
const isDirty     = git("git status --porcelain") !== "";
const buildTime   = new Date().toISOString();

const meta = {
  name:        pkg.name,
  version:     pkg.version,
  description: pkg.description,
  commitHash,
  commitDate,
  branch,
  isDirty,
  buildTime,
  nodeVersion: process.version,
};

// 1. Write dist/version-meta.json (consumed by CLI at runtime)
mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(
  join(ROOT, "dist", "version-meta.json"),
  JSON.stringify(meta, null, 2),
  "utf-8"
);

// 2. Write src/version.ts (checked-in generated file, imported by TypeScript)
const ts = `// ⚠️  Auto-generated by scripts/embed-version.mjs — do not edit manually.
// Run \`npm run build\` to regenerate.

export const VERSION_META = ${JSON.stringify(meta, null, 2)} as const;

export type VersionMeta = typeof VERSION_META;
`;

writeFileSync(join(ROOT, "src", "version.ts"), ts, "utf-8");

console.log(`✔ Version metadata embedded: v${meta.version} (${commitHash || "no-git"})`);
